### ISSUE TITLE
improve the ui of create section

### ISSUE THREAD

**Issue by ShravaniAK** [abhinavkashyap061/blog#24]

**Comment by Kritika30032002** [comment]
can i contribute to this?

**Comment by abhinavkashyap061** [comment]
@ShravaniAK sure, I am assigning you this task 👍

**Comment by abhinavkashyap061** [comment]
@Kritika30032002 You can raise a PR for same, if it's better I will merge it. Or go through other issues / raise new one about new feature or fix a bug.

**Comment by Kritika30032002** [comment]
> @ShravaniAK sure, I am assigning you this task 👍

She haven't mentioned it anywhere that she want to do this 

therefore u can assign it to me

**Comment by abhinavkashyap061** [comment]
> > @ShravaniAK sure, I am assigning you this task 👍
> 
> She haven't mentioned it anywhere that she want to do this
> 
> therefore u can assign it to me

Ok sure @Kritika30032002 , I am assigning you this 👍

**Comment by Kritika30032002** [comment]
> > > @ShravaniAK sure, I am assigning you this task 👍
> > 
> > 
> > She haven't mentioned it anywhere that she want to do this
> > therefore u can assign it to me
> 
> Ok sure @Kritika30032002 , I am assigning you this 👍

okay
