### ISSUE TITLE
Want to change UI of About Page

### ISSUE THREAD

**Issue by Delvitron1019** [abhinavkashyap061/blog#32]

**Comment by Kritika30032002** [comment]
you can assign this to me...

**Comment by krishnabiradar310802** [comment]
@Delvitron1019 can you assign me this issue under hacktoberfest label?

**Comment by Kritika30032002** [comment]
> you can assign this to me...

@abhinavkashyap061

**Comment by abhinavkashyap061** [comment]
@Delvitron1019 Sure, I am assigning you this 👍

**Comment by Kritika30032002** [comment]
> @Delvitron1019 Sure, I am assigning you this 👍


He haven't mentioned it anywhere that he want to do this 

therefore u can assign it to me

**Comment by abhinavkashyap061** [comment]
> > @Delvitron1019 Sure, I am assigning you this 👍
> 
> He haven't mentioned it anywhere that he want to do this
> 
> therefore u can assign it to me

Ok sure @Kritika30032002 , I am assigning you this 👍

**Comment by Kritika30032002** [comment]
> > > @Delvitron1019 Sure, I am assigning you this 👍
> > 
> > 
> > He haven't mentioned it anywhere that he want to do this
> > therefore u can assign it to me
> 
> Ok sure @Kritika30032002 , I am assigning you this 👍

okay

**Comment by Kritika30032002** [comment]
@abhinavkashyap061 

site is not opening now

![Screenshot (19463)](https://user-images.githubusercontent.com/83400697/196253471-e54a5a4b-251d-43b1-b07a-d122aba933f0.png)

**Comment by abhinavkashyap061** [comment]
> @abhinavkashyap061
> 
> site is not opening now
> 
> ![Screenshot (19463)](https://user-images.githubusercontent.com/83400697/196253471-e54a5a4b-251d-43b1-b07a-d122aba933f0.png)

yeah I have ran out of Heroku free tier, please run it locally for now. I will deploy it somewhere else soon

**Comment by Kritika30032002** [comment]
okay

**Comment by Delvitron1019** [comment]
@Kritika30032002  @abhinavkashyap061  sorry but this ain't fair all of us are contributors I have state this issue first and deserve to work on this I think issues are assigned on the basis of first come first server basis.

**Comment by Delvitron1019** [comment]
@abhinavkashyap061 I started working on it and now you just unassigned it without even asking me. Please assign it back to me

**Comment by abhinavkashyap061** [comment]
Ok sure @Delvitron1019 👍

**Comment by laveshverma007** [comment]
Please assign this to me

**Comment by Delvitron1019** [comment]
@laveshverma007 , you can have it. @abhinavkashyap061 I am ok with @laveshverma007 resolving this issue
