### ISSUE TITLE
Want to add dark and light mode button

### ISSUE THREAD

**Issue by Delvitron1019** [abhinavkashyap061/blog#33]

**Comment by krishnabiradar310802** [comment]
@Delvitron1019 can you assign me this issue under hacktoberfest label?

**Comment by RegishShrestha** [comment]
Can you assign me this issue?

**Comment by abhinavkashyap061** [comment]
Who's going to do this? I am confused 😂

**Comment by Delvitron1019** [comment]
@abhinavkashyap061 I created this issue and I deserve to do this

**Comment by Delvitron1019** [comment]
@abhinavkashyap061 please allow me to complete this issue as I have started to work on it and invested some of my time in it so please assign it to me.

**Comment by abhinavkashyap061** [comment]
> @abhinavkashyap061 please allow me to complete this issue as I have started to work on it and invested some of my time in it so please assign it to me.

Ok sure @Delvitron1019 I am assigning you this task 👍
